name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install git make wget gcc unzip bzip2
          ./build.sh goke
          ./build.sh hisi
          ./build.sh star6b0
          ./build.sh star6e
          ./build.sh x86

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          path: |
              wfb_bind_goke
              wfb_bind_hisi
              wfb_bind_star6b0
              wfb_bind_star6e
              wfb_bind_x86

      - name: Versioned release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            wfb_bind_goke
            wfb_bind_hisi
            wfb_bind_star6b0
            wfb_bind_star6e
            wfb_bind_x86

      - name: Upload latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            wfb_bind_goke
            wfb_bind_hisi
            wfb_bind_star6b0
            wfb_bind_star6e
            wfb_bind_x86
